version: '3'
services:

  api:
    build: ./backend
    ports:
      - 7000:8000
    volumes:
      - ./backend:/home/node/mag-engine
      - /usr/bin/docker:/usr/bin/docker
      - /usr/bin/docker-compose:/usr/bin/docker-compose
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/Documents/mag/bricks/redactor/backend:/home/node/mag-engine/bricks # tmp
      - ./apps:/home/node/mag-engine/apps
    depends_on:
      - mongo
    entrypoint: ./entrypoint.sh

  mongo:
    image: mongo:3.0-wheezy
    ports:
      - 27017
    volumes:
       - ./backend/database:/data/db

  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/dist:/dist
    depends_on:
      - api
    ports:
      - 5555:80
    
