version: '3'
services:

  api:
    build: .
    ports:
      - 7000:8000
    volumes:
      - .:/home/node/mag-engine
    depends_on:
      - mongo

  mongo:
    image: mongo:3.0-wheezy
    ports:
      - 27017
    volumes:
       - ./database:/data/db