version: '3'
services:
  server:
    build: ./backend
    ports:
      - 8000
    volumes:
      - ./backend/:/home/node/brickdev
    depends_on:
      - mongo

  mongo:
    image: mongo:3.0-wheezy
    ports:
      - 27017
    volumes:
        - ./backend/database:/data/db