version: '3'
services:

  server:
    build: ./backend
    ports:
      - @MAG_SERVER_SERVER_PORT@:8000
    volumes:
      - @MAG_ENGINE_BASE_PATH@mag/mag-engine/apps/@APP_NAME@/backend:/home/node/mag-server #absolute path!
      - @MAG_ENGINE_BASE_PATH@mag/mag-engine/apps/@APP_NAME@/frontend:/home/node/mag-server/frontend #absolute path!
      - @MAG_ENGINE_BASE_PATH@mag/mag-engine/apps/@APP_NAME@/nginx:/home/node/mag-server/nginx #absolute path!
      - @MAG_ENGINE_BASE_PATH@mag/bricks:/home/node/bricks-repo #absolute path!
      - @MAG_ENGINE_BASE_PATH@mag/mag-engine/apps/@APP_NAME@/bricks:/home/node/mag-server/bricks #absolute path!
      - /usr/bin/docker:/usr/bin/docker
      - /usr/bin/docker-compose:/usr/bin/docker-compose
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/webpack:/usr/bin/webpack
    depends_on:
      - mongo
    entrypoint: ./entrypoint.sh
    environment:
      - SERVER_PORT_NUMBER=@SERVER_PORT_NUMBER@
      - NGINX_PORT_NUMBER=@NGINX_PORT_NUMBER@
      - BASE_PATH=@MAG_ENGINE_BASE_PATH@

  mongo:
    image: mongo:3.0-wheezy
    ports:
      - 27017
    volumes:
       - @MAG_ENGINE_BASE_PATH@mag/mag-engine/apps/@APP_NAME@/backend/database:/data/db       #absolute path!

  nginx:
    image: nginx
    volumes:
      - @MAG_ENGINE_BASE_PATH@mag/mag-engine/apps/@APP_NAME@/nginx/conf.d:/etc/nginx/conf.d   #absolute path!
      - @MAG_ENGINE_BASE_PATH@mag/mag-engine/apps/@APP_NAME@/frontend/app/dist:/dist          #absolute path!
    depends_on:
      - server
    ports:
      - @MAG_SERVER_NGINX_PORT@:80
    
