version: '3'
services:

  server:
    build: ./backend
    ports:
      - 12000:8000
    volumes:
      - ./backend/:/home/node/mag-server
      - /usr/bin/docker-compose:/usr/bin/docker-compose
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/home/node/mag-server
    depends_on:
      - mongo

  mongo:
    image: mongo:3.0-wheezy
    ports:
      - 27017
    volumes:
       - ./backend/database:/data/db

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/app/dist:/dist
    depends_on:
      - server
    ports:
      - 11000:80
    
