version: '3'
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 9000:8000
    volumes:
      - /home/jlink/Documents/abCd/mag-server/bricks/abCd-redactor:/home/node/brickdev # absolute path
    depends_on:
      - mongo

  mongo:
    image: mongo:3.0-wheezy
    ports:
      - 27017
    volumes:
      - /home/jlink/Documents/abCd/mag-server/bricks/abCd-redactor/database:/data/db # absolute path

      #/home/jlink/Documents/mag/mag-engine/apps